from dataclasses import dataclass, field


@dataclass
class ModuleMergerOptions:
    ignore_imports: list[str] = field(default_factory=lambda: [])
    remove_imports: list[str] = field(default_factory=lambda: [])
    docstring: str | None = """ Generated by python-minifier. """
    prelude: str | None = None
    compile_time_constants: dict[str, str | bool | int | float] = field(
        default_factory=lambda: {})
