from dataclasses import dataclass, field


@dataclass
class ModuleMergerOptions:
    ignore_imports: list[str] = field(default_factory=lambda: [])
    docstring: str = """ Generated by python-module-merger. """
